<x-app-layout layout='social' title="Event List">
    <div class="d-grid gap-3 d-grid-template-1fr-19">
         <x-modules.social.widgets.event-card eventCardMonths="Jan" img="19.png" eventCardDate="01" eventCardTitle="New Year Celibration" eventCardDec="Lorem Ipsum is simply dummy text" eventCardimg1="01.png" eventCardimg2="02.png" eventCardimg3="03.png" eventCardimg4="04.png" eventCardimg5="05.png" classname="mb-0" />
         <x-modules.social.widgets.event-card eventCardMonths="Jan" img="02.png" eventCardDate="24" eventCardTitle="Birthday Celibration" eventCardDec="Lorem Ipsum is simply dummy text" eventCardimg1="01.png" eventCardimg2="02.png" eventCardimg3="03.png" eventCardimg4="04.png" eventCardimg5="05.png" classname="mb-0" />
         <x-modules.social.widgets.event-card eventCardMonths="Jan" img="03.png" eventCardDate="26" eventCardTitle="Republic Day" eventCardDec="Lorem Ipsum is simply dummy text" eventCardimg1="01.png" eventCardimg2="02.png" eventCardimg3="03.png" eventCardimg4="04.png" eventCardimg5="05.png" classname="mb-0" />
         <x-modules.social.widgets.event-card eventCardMonths="Feb" img="04.png" eventCardDate="04" eventCardTitle="Meetings & Conventions" eventCardDec="Lorem Ipsum is simply dummy text" eventCardimg1="01.png" eventCardimg2="02.png" eventCardimg3="03.png" eventCardimg4="04.png" eventCardimg5="05.png" classname="mb-0" />
         <x-modules.social.widgets.event-card eventCardMonths="March" img="05.png" eventCardDate="01" eventCardTitle="Fun Events and Festivals" eventCardDec="Lorem Ipsum is simply dummy text" eventCardimg1="01.png" eventCardimg2="02.png" eventCardimg3="03.png" eventCardimg4="04.png" eventCardimg5="05.png" classname="mb-0" />
         <x-modules.social.widgets.event-card eventCardMonths="March" img="06.png" eventCardDate="10" eventCardTitle="Atlanta Retail Show" eventCardDec="Lorem Ipsum is simply dummy text" eventCardimg1="01.png" eventCardimg2="02.png" eventCardimg3="03.png" eventCardimg4="04.png" eventCardimg5="05.png" classname="mb-0" />
         <x-modules.social.widgets.event-card eventCardMonths="March" img="07.png" eventCardDate="14" eventCardTitle="Holi in the City" eventCardDec="Lorem Ipsum is simply dummy text" eventCardimg1="01.png" eventCardimg2="02.png" eventCardimg3="03.png" eventCardimg4="04.png" eventCardimg5="05.png" classname="mb-0 mb-lg-3"/>
         <x-modules.social.widgets.event-card eventCardMonths="Mar" img="08.png" eventCardDate="16" eventCardTitle="Insurance Innovators" eventCardDec="Lorem Ipsum is simply dummy text" eventCardimg1="01.png" eventCardimg2="02.png" eventCardimg3="03.png" eventCardimg4="04.png" eventCardimg5="05.png"  classname="mb-0 mb-lg-3"/>
         <x-modules.social.widgets.event-card eventCardMonths="Apr" img="09.png" eventCardDate="12" eventCardTitle="BIG 5G Event" eventCardDec="Lorem Ipsum is simply dummy text" eventCardimg1="01.png" eventCardimg2="02.png" eventCardimg3="03.png" eventCardimg4="04.png" eventCardimg5="05.png" classname="mb-3" />
    </div>

</x-app-layout>
