<x-app-layout layout="social" title="Group List">
    <div class="d-grid gap-3 d-grid-template-1fr-19">
        <x-modules.social.widgets.group img="01.png" groupimg="01.jpg" groupTitle="Designer" groupDec="Lorem Ipsum data" groupPost="Post" groupPostNumber="600" groupMember="Member" groupMemberNumber="320" groupVisit="Visit" groupVisitNumber="1.2k" groupAvatarimg="01.png" groupAvatarimg1="02.png" groupAvatarimg2="03.png" groupAvatarimg3="04.png" groupAvatarimg4="05.png" groupAvatarimg5="06.png" classname="mb-0"/>
        <x-modules.social.widgets.group img="02.png" groupimg="02.jpg" groupTitle="R & D"    groupDec="Lorem Ipsum data" groupPost="Post" groupPostNumber="300" groupMember="Member" groupMemberNumber="210" groupVisit="Visit" groupVisitNumber="1.1k" groupAvatarimg="01.png" groupAvatarimg1="02.png" groupAvatarimg2="03.png" groupAvatarimg3="04.png" groupAvatarimg4="05.png" groupAvatarimg5="06.png" classname="mb-0"/>
        <x-modules.social.widgets.group img="03.png" groupimg="03.jpg" groupTitle="Graphics" groupDec="Lorem Ipsum data" groupPost="Post" groupPostNumber="320" groupMember="Member" groupMemberNumber="100" groupVisit="Visit" groupVisitNumber="1.0k" groupAvatarimg="01.png" groupAvatarimg1="02.png" groupAvatarimg2="03.png" groupAvatarimg3="04.png" groupAvatarimg4="05.png" groupAvatarimg5="06.png" classname="mb-0"/>
        <x-modules.social.widgets.group img="04.png" groupimg="04.jpg" groupTitle="Developer" groupDec="Lorem Ipsum data" groupPost="Post" groupPostNumber="800" groupMember="Member" groupMemberNumber="480" groupVisit="Visit" groupVisitNumber="2.2k" groupAvatarimg="01.png" groupAvatarimg1="02.png" groupAvatarimg2="03.png" groupAvatarimg3="04.png" groupAvatarimg4="05.png" groupAvatarimg5="06.png" classname="mb-0"/>
        <x-modules.social.widgets.group img="05.png" groupimg="05.jpg" groupTitle="Tester" groupDec="Lorem Ipsum data" groupPost="Post" groupPostNumber="200" groupMember="Member" groupMemberNumber="100" groupVisit="Visit" groupVisitNumber="32" groupAvatarimg="01.png" groupAvatarimg1="02.png" groupAvatarimg2="03.png" groupAvatarimg3="04.png" groupAvatarimg4="05.png" groupAvatarimg5="06.png" classname="mb-0"/>
        <x-modules.social.widgets.group img="06.png" groupimg="06.jpg" groupTitle="Events" groupDec="Lorem Ipsum data" groupPost="Post" groupPostNumber="1000" groupMember="Member" groupMemberNumber="500" groupVisit="Visit" groupVisitNumber="3.2k" groupAvatarimg="01.png" groupAvatarimg1="02.png" groupAvatarimg2="03.png" groupAvatarimg3="04.png" groupAvatarimg4="05.png" groupAvatarimg5="06.png" classname="mb-0"/>
        <x-modules.social.widgets.group img="07.png" groupimg="07.jpg" groupTitle="Coder" groupDec="Lorem Ipsum data" groupPost="Post" groupPostNumber="300" groupMember="Member" groupMemberNumber="220" groupVisit="Visit" groupVisitNumber="25k" groupAvatarimg="01.png" groupAvatarimg1="02.png" groupAvatarimg2="03.png" groupAvatarimg3="04.png" groupAvatarimg4="05.png" groupAvatarimg5="06.png" classname="mb-0 mb-lg-3"/>
        <x-modules.social.widgets.group img="08.png" groupimg="08.jpg" groupTitle="Themes" groupDec="Lorem Ipsum data" groupPost="Post" groupPostNumber="1200" groupMember="Member" groupMemberNumber="800" groupVisit="Visit" groupVisitNumber="3.2k" groupAvatarimg="01.png" groupAvatarimg1="02.png" groupAvatarimg2="03.png" groupAvatarimg3="04.png" groupAvatarimg4="05.png" groupAvatarimg5="06.png" classname="mb-0 mb-lg-3"/>
        
        <x-modules.social.widgets.group img="01.png" groupimg="09.jpg" groupTitle="Review" groupDec="Lorem Ipsum data" groupPost="Post" groupPostNumber="300" groupMember="Member" groupMemberNumber="1000" groupVisit="Visit" groupVisitNumber="4.5k" groupAvatarimg="01.png" groupAvatarimg1="02.png" groupAvatarimg2="03.png" groupAvatarimg3="04.png" groupAvatarimg4="05.png" groupAvatarimg5="06.png" classname="mb-3"/>
       
    </div>
</x-app-layout>
